# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGridLayout, QLabel, QLineEdit,
    QMainWindow, QPushButton, QSizePolicy, QStatusBar,
    QTabWidget, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(676, 511)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.clock = QTabWidget(self.centralwidget)
        self.clock.setObjectName(u"clock")
        self.clock.setGeometry(QRect(10, 10, 641, 461))
        self.timer = QWidget()
        self.timer.setObjectName(u"timer")
        self.Timer_hour = QLineEdit(self.timer)
        self.Timer_hour.setObjectName(u"Timer_hour")
        self.Timer_hour.setGeometry(QRect(150, 30, 61, 71))
        font = QFont()
        font.setFamilies([u"7 Segments Display"])
        font.setPointSize(27)
        font.setBold(True)
        self.Timer_hour.setFont(font)
        self.Timer_second = QLineEdit(self.timer)
        self.Timer_second.setObjectName(u"Timer_second")
        self.Timer_second.setGeometry(QRect(330, 30, 61, 71))
        self.Timer_second.setFont(font)
        self.Timer_minute = QLineEdit(self.timer)
        self.Timer_minute.setObjectName(u"Timer_minute")
        self.Timer_minute.setGeometry(QRect(240, 30, 61, 71))
        self.Timer_minute.setFont(font)
        self.label = QLabel(self.timer)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(220, 40, 16, 41))
        font1 = QFont()
        font1.setPointSize(30)
        font1.setBold(True)
        self.label.setFont(font1)
        self.label_2 = QLabel(self.timer)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(310, 40, 16, 41))
        self.label_2.setFont(font1)
        self.btn_timer_start = QPushButton(self.timer)
        self.btn_timer_start.setObjectName(u"btn_timer_start")
        self.btn_timer_start.setGeometry(QRect(140, 130, 75, 24))
        self.btn_timer_stop = QPushButton(self.timer)
        self.btn_timer_stop.setObjectName(u"btn_timer_stop")
        self.btn_timer_stop.setGeometry(QRect(230, 130, 75, 24))
        self.btn_timer_reset = QPushButton(self.timer)
        self.btn_timer_reset.setObjectName(u"btn_timer_reset")
        self.btn_timer_reset.setGeometry(QRect(320, 130, 75, 24))
        self.clock.addTab(self.timer, "")
        self.stopwatch = QWidget()
        self.stopwatch.setObjectName(u"stopwatch")
        self.btn_stopwatch_reset = QPushButton(self.stopwatch)
        self.btn_stopwatch_reset.setObjectName(u"btn_stopwatch_reset")
        self.btn_stopwatch_reset.setGeometry(QRect(350, 100, 75, 24))
        self.btn_stopwatch_start = QPushButton(self.stopwatch)
        self.btn_stopwatch_start.setObjectName(u"btn_stopwatch_start")
        self.btn_stopwatch_start.setGeometry(QRect(170, 100, 75, 24))
        self.label_4 = QLabel(self.stopwatch)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(240, 30, 16, 41))
        self.label_4.setFont(font1)
        self.btn_stopwatch_stop = QPushButton(self.stopwatch)
        self.btn_stopwatch_stop.setObjectName(u"btn_stopwatch_stop")
        self.btn_stopwatch_stop.setGeometry(QRect(260, 100, 75, 24))
        self.label_3 = QLabel(self.stopwatch)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(320, 30, 16, 41))
        self.label_3.setFont(font1)
        self.lbl_stopwatch_hour = QLabel(self.stopwatch)
        self.lbl_stopwatch_hour.setObjectName(u"lbl_stopwatch_hour")
        self.lbl_stopwatch_hour.setGeometry(QRect(190, 30, 49, 51))
        font2 = QFont()
        font2.setFamilies([u"7 Segments Display"])
        font2.setPointSize(20)
        font2.setBold(True)
        self.lbl_stopwatch_hour.setFont(font2)
        self.lbl_stopwatch_minute = QLabel(self.stopwatch)
        self.lbl_stopwatch_minute.setObjectName(u"lbl_stopwatch_minute")
        self.lbl_stopwatch_minute.setGeometry(QRect(270, 30, 49, 51))
        self.lbl_stopwatch_minute.setFont(font2)
        self.lbl_stopwatch_second = QLabel(self.stopwatch)
        self.lbl_stopwatch_second.setObjectName(u"lbl_stopwatch_second")
        self.lbl_stopwatch_second.setGeometry(QRect(340, 30, 49, 51))
        self.lbl_stopwatch_second.setFont(font2)
        self.clock.addTab(self.stopwatch, "")
        self.worldclock = QWidget()
        self.worldclock.setObjectName(u"worldclock")
        self.lbl_Iran = QLabel(self.worldclock)
        self.lbl_Iran.setObjectName(u"lbl_Iran")
        self.lbl_Iran.setGeometry(QRect(20, 10, 81, 61))
        self.lbl_Iran.setFont(font1)
        self.lbl_USA = QLabel(self.worldclock)
        self.lbl_USA.setObjectName(u"lbl_USA")
        self.lbl_USA.setGeometry(QRect(340, 10, 91, 71))
        self.lbl_USA.setFont(font1)
        self.lbl_Germany = QLabel(self.worldclock)
        self.lbl_Germany.setObjectName(u"lbl_Germany")
        self.lbl_Germany.setGeometry(QRect(10, 160, 181, 61))
        self.lbl_Germany.setFont(font1)
        self.lbl_worldclock_iran = QLabel(self.worldclock)
        self.lbl_worldclock_iran.setObjectName(u"lbl_worldclock_iran")
        self.lbl_worldclock_iran.setGeometry(QRect(20, 70, 241, 41))
        self.lbl_worldclock_iran.setFont(font2)
        self.lbl_worldclock_usa = QLabel(self.worldclock)
        self.lbl_worldclock_usa.setObjectName(u"lbl_worldclock_usa")
        self.lbl_worldclock_usa.setGeometry(QRect(330, 70, 241, 41))
        self.lbl_worldclock_usa.setFont(font2)
        self.lbl_worldclock_germany = QLabel(self.worldclock)
        self.lbl_worldclock_germany.setObjectName(u"lbl_worldclock_germany")
        self.lbl_worldclock_germany.setGeometry(QRect(20, 220, 241, 41))
        self.lbl_worldclock_germany.setFont(font2)
        self.clock.addTab(self.worldclock, "")
        self.alarm = QWidget()
        self.alarm.setObjectName(u"alarm")
        self.my_alarm = QTabWidget(self.alarm)
        self.my_alarm.setObjectName(u"my_alarm")
        self.my_alarm.setGeometry(QRect(30, 10, 561, 381))
        self.alarm1 = QWidget()
        self.alarm1.setObjectName(u"alarm1")
        self.Timer_hour_3 = QLineEdit(self.alarm1)
        self.Timer_hour_3.setObjectName(u"Timer_hour_3")
        self.Timer_hour_3.setGeometry(QRect(130, 20, 61, 71))
        self.Timer_hour_3.setFont(font)
        self.label_9 = QLabel(self.alarm1)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(290, 30, 16, 41))
        self.label_9.setFont(font1)
        self.Timer_minute_3 = QLineEdit(self.alarm1)
        self.Timer_minute_3.setObjectName(u"Timer_minute_3")
        self.Timer_minute_3.setGeometry(QRect(220, 20, 61, 71))
        self.Timer_minute_3.setFont(font)
        self.label_10 = QLabel(self.alarm1)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(200, 30, 16, 41))
        self.label_10.setFont(font1)
        self.Timer_second_3 = QLineEdit(self.alarm1)
        self.Timer_second_3.setObjectName(u"Timer_second_3")
        self.Timer_second_3.setGeometry(QRect(310, 20, 61, 71))
        self.Timer_second_3.setFont(font)
        self.lineEdit = QLineEdit(self.alarm1)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(130, 100, 241, 41))
        self.label_11 = QLabel(self.alarm1)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(40, 100, 101, 41))
        font3 = QFont()
        font3.setFamilies([u"Arial"])
        font3.setPointSize(11)
        font3.setBold(True)
        self.label_11.setFont(font3)
        self.btn_add_alarm = QPushButton(self.alarm1)
        self.btn_add_alarm.setObjectName(u"btn_add_alarm")
        self.btn_add_alarm.setGeometry(QRect(130, 150, 241, 41))
        font4 = QFont()
        font4.setPointSize(16)
        font4.setBold(True)
        self.btn_add_alarm.setFont(font4)
        self.my_alarm.addTab(self.alarm1, "")
        self.alarms = QWidget()
        self.alarms.setObjectName(u"alarms")
        self.gridLayoutWidget = QWidget(self.alarms)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(10, 10, 531, 321))
        self.show_alarms = QGridLayout(self.gridLayoutWidget)
        self.show_alarms.setObjectName(u"show_alarms")
        self.show_alarms.setContentsMargins(0, 0, 0, 0)
        self.my_alarm.addTab(self.alarms, "")
        self.clock.addTab(self.alarm, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.clock.setCurrentIndex(3)
        self.my_alarm.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.Timer_hour.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.Timer_second.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.Timer_minute.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u":", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u":", None))
        self.btn_timer_start.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.btn_timer_stop.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.btn_timer_reset.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.clock.setTabText(self.clock.indexOf(self.timer), QCoreApplication.translate("MainWindow", u"Timer", None))
        self.btn_stopwatch_reset.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.btn_stopwatch_start.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u":", None))
        self.btn_stopwatch_stop.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u":", None))
        self.lbl_stopwatch_hour.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.lbl_stopwatch_minute.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.lbl_stopwatch_second.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.clock.setTabText(self.clock.indexOf(self.stopwatch), QCoreApplication.translate("MainWindow", u"StopWatch", None))
        self.lbl_Iran.setText(QCoreApplication.translate("MainWindow", u"Iran", None))
        self.lbl_USA.setText(QCoreApplication.translate("MainWindow", u"USA", None))
        self.lbl_Germany.setText(QCoreApplication.translate("MainWindow", u"Germany", None))
        self.lbl_worldclock_iran.setText(QCoreApplication.translate("MainWindow", u"00 : 00 : 00", None))
        self.lbl_worldclock_usa.setText(QCoreApplication.translate("MainWindow", u"00 : 00 : 00", None))
        self.lbl_worldclock_germany.setText(QCoreApplication.translate("MainWindow", u"00 : 00 : 00", None))
        self.clock.setTabText(self.clock.indexOf(self.worldclock), QCoreApplication.translate("MainWindow", u"WorldClock", None))
        self.Timer_hour_3.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u":", None))
        self.Timer_minute_3.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u":", None))
        self.Timer_second_3.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Name Alarm:", None))
        self.btn_add_alarm.setText(QCoreApplication.translate("MainWindow", u"Add Alarm", None))
        self.my_alarm.setTabText(self.my_alarm.indexOf(self.alarm1), QCoreApplication.translate("MainWindow", u"Add Alarm", None))
        self.my_alarm.setTabText(self.my_alarm.indexOf(self.alarms), QCoreApplication.translate("MainWindow", u"Alarms", None))
        self.clock.setTabText(self.clock.indexOf(self.alarm), QCoreApplication.translate("MainWindow", u"Alarm", None))
    # retranslateUi

